"""
SQLAlchemy schema generation from Pydantic models.

This module provides a clean intermediate representation for defining database schemas
that can be generated by LLMs using structured output, then converted to SQLAlchemy
Table objects.

Main classes:
    - DatabaseSchema: Top-level schema containing multiple tables
    - TableDefinition: Definition of a single table
    - ColumnDefinition: Definition of a table column
    - ForeignKeyDefinition: Foreign key constraint
    - IndexDefinition: Index definition
    - UniqueConstraint: Multi-column unique constraint
    - CheckConstraint: Check constraint

Enums:
    - SQLColumnType: Supported column types
    - ForeignKeyAction: Foreign key actions (CASCADE, SET NULL, etc.)
    - IndexType: Index types (BTREE, HASH, etc.)

Functions:
    - create_sqlalchemy_tables: Convert DatabaseSchema to SQLAlchemy Tables
    - create_database_schema: Convenience function to create schema in database

Example:
    >>> from schema_gen import generate_sqlalchemy_models_from_prompt, create_sqlalchemy_tables
    >>> from sqlalchemy import MetaData
    >>>
    >>> schema = generate_sqlalchemy_models_from_prompt(
    ...     "Create a blog schema with users and posts",
    ...     model="openai/gpt-4.1-mini",
    ... )
    >>> metadata = MetaData()
    >>> tables = create_sqlalchemy_tables(schema, metadata)
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional, Dict

# Minimal utility classes needed by the package


class StrEnum(str, Enum):
    """String enumeration base class."""

    def __str__(self):
        return str(self.value)

    @classmethod
    def validate(cls, value):
        if value not in cls._value2member_map_:
            raise ValueError(f"{value} is not a valid {cls.__name__}")


@dataclass(kw_only=True)
class DBCredentials:
    """Database credentials for connection."""

    user: str
    password: str
    host: str
    port: Optional[str] = None
    database: Optional[str] = None
    engine: str = "postgres"

    def __str__(self) -> str:
        return f"DBCredentials(user={self.user}, password={self.password}, host={self.host}, port={self.port}, database={self.database}, engine={self.engine})"

    def __dict__(self) -> Dict[str, str]:
        data = {
            "user": self.user,
            "password": self.password,
            "host": self.host,
            "port": self.port,
            "database": self.database,
            "engine": self.engine,
        }
        return {k: v for k, v in data.items() if v is not None}

    def to_dict(self) -> Dict[str, str]:
        """Convert credentials to dictionary."""
        return self.__dict__()

    def with_database(self, database: str) -> "DBCredentials":
        """Create a new DBCredentials object with the same credentials but different database name."""
        kwargs = self.to_dict()
        kwargs["database"] = database
        return DBCredentials(**kwargs)

    def to_url(self, is_async: bool = False):
        """Convert credentials to SQLAlchemy URL (PostgreSQL only)."""
        import sqlalchemy.engine

        if self.engine != "postgres":
            raise NotImplementedError(f"to_url only supports postgres engine, got {self.engine}")

        if not self.database:
            raise ValueError("database is required to create a URL")

        url_kwargs = self.to_dict()
        if is_async:
            url_kwargs["drivername"] = "postgresql+asyncpg"
        else:
            url_kwargs["drivername"] = "postgresql+psycopg2"

        # Unix sockets and regular hosts both go in the host query parameter
        host = url_kwargs.pop("host", None)
        if host:
            url_kwargs["query"] = {"host": host}

        if username := url_kwargs.pop("user", None):
            url_kwargs["username"] = username

        # Remove engine from url_kwargs as it's not needed by SQLAlchemy
        url_kwargs.pop("engine", None)

        return sqlalchemy.engine.URL.create(**url_kwargs)


# Export main classes
from schema_gen.models import (
    DatabaseSchema,
    TableDefinition,
    ColumnDefinition,
    ForeignKeyDefinition,
    IndexDefinition,
    CheckConstraint,
    UniqueConstraint,
    TypeParameter,
)
from schema_gen.enums import (
    SQLColumnType,
    ForeignKeyAction,
    IndexType,
)
from schema_gen.llm_generator import (
    generate_sqlalchemy_models_from_prompt,
    post_process_schema,
)
from schema_gen.setup_db import (
    setup_database,
    validate_database_identifier,
)

__all__ = [
    # Utility classes
    "StrEnum",
    "DBCredentials",
    # Main models
    "DatabaseSchema",
    "TableDefinition",
    "ColumnDefinition",
    "ForeignKeyDefinition",
    "IndexDefinition",
    "CheckConstraint",
    "UniqueConstraint",
    "TypeParameter",
    # Enums
    "SQLColumnType",
    "ForeignKeyAction",
    "IndexType",
    # Functions
    "generate_sqlalchemy_models_from_prompt",
    "post_process_schema",
    "setup_database",
    "validate_database_identifier",
]
